#!/bin/sh
# sets the status bar
while true
do
    xsetroot -name "Wlan0: $(iwconfig wlan0 | awk '/Quality/{print $2}' | sed 's/.*=//' | awk -F"/" '{printf("%.0f%%", $1/$2*100)}') | Mem: $(free -m | perl -ne 'if(/cache:\s+(\d+)/) {printf $1;last;}') mb | CPU: $(mpstat | perl -ne 'if(/all\s+(\d+\.\d+)/) {printf $1;last;}')% | Bat: $(acpi | perl -ne 'if(/0:\s+([^%]+)/) {print $1."%";}') | $(date +"%a, %b %d %R")"
    sleep 10s   
done 