#!/bin/sh
#-*- sh -*-
##
# This simple script selects a random image from a specified directory and sets it as the wallpaper in an infinite loop.
# Depends on feh.
##
if [ -z $1 ]
then
    echo "Usage: $0 <wallpaper directory> [time]"
    exit 65
fi

if [ ! -d $1 ]
then
    echo "Supplied argument is not a directory."
    exit 65
fi

stime=$2
if [ -z $stime ]
then
    echo "No sleep time supplied, setting it to 120s"
    stime=120
fi

while :
do
    img=`ls $1 -1 | shuf -n 1`
    feh --bg-scale $1"/"$img
    echo "Set $img as  wallpaper"
    sleep $stime
done
